version: '3.7'
services:
  portal:
    container_name: portal
    image: nginx  
    ports:
      - 8080:80
    volumes: 
      - /home/ramki/cluster/default.conf:/etc/nginx/conf.d/default.conf
  tomcat1:
    image: tomcat:7.0.94-jre7-alpine
    container_name: tomcat1
    volumes:
      - /home/ramki/cluster/server.xml:/usr/local/tomcat/conf/server.xml
      - /home/ramki/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
      - /home/ramki/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  tomcat2:
    image: tomcat:7.0.94-jre7-alpine
    container_name: tomcat2
    volumes:
      - /home/ramki/cluster/server.xml:/usr/local/tomcat/conf/server.xml
      - /home/ramki/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
      - /home/ramki/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  tomcat3:
    image: tomcat:7.0.94-jre7-alpine
    container_name: tomcat3
    volumes:
      - /home/ramki/cluster/server.xml:/usr/local/tomcat/conf/server.xml
      - /home/ramki/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
      - /home/ramki/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml 
