services:
  portal:
    image: nginx:1.27.2-alpine
    ports:
     - "8888:80"
    volumes:
     - ./cluster/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tomcat-cluster
    depends_on:
      tomcat:
        condition: service_healthy

  tomcat:
    image: tomcat:11.0.1-jdk21-temurin-noble
    deploy:
      replicas: 3
    networks:
      tomcat-cluster:
        aliases:
          - "backend"
    volumes:
     - ./cluster/server.xml:/usr/local/tomcat/conf/server.xml
     - ./cluster/ROOT:/usr/local/tomcat/webapps/ROOT
     - ./cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/ || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 120

networks:
  tomcat-cluster: {}
